### ISSUE TITLE
EmailTemplate throws 'done is not a function'

### ISSUE THREAD

**Issue by blagoberry** [crocodilejs/node-email-templates#186]
Hi!

I am trying to get node mailer to work using EmailTemplate as the template engine. My code started throwing errors like the one below. I checked where the error was coming from, my code or not, and I can still reproduce it using simply: 

const tmp = new EmailTemplate(templateDir);

I am relatively new to the JS world, but from reading around this seems to be a promises-related issue. Could it be that Email Template doesn't like the type of promises I am using? (ES6 + Babel, I presume the underlying Promise object is the standard spec one)

Is there a way to stop the constructor from throwing? That'd be lovely :-)

Thanks,
Blago

```
/.../node_modules/email-templates/node_modules/bluebird/js/release/async.js:61
[2]         fn = function () { throw arg; };
[2]                            ^
[2] 
[2] TypeError: done is not a function
[2]     at /Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/lib/main.js:28:12
[2]     at tryCatcher (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/util.js:16:23)
[2]     at Promise.successAdapter [as _fulfillmentHandler0] (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/nodeify.js:22:30)
[2]     at Promise._settlePromise (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:558:21)
[2]     at Promise._settlePromise0 (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:606:10)
[2]     at Promise._settlePromises (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/promise.js:685:18)
[2]     at Async._drainQueue (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/async.js:138:16)
[2]     at Async._drainQueues (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/async.js:148:10)
[2]     at Immediate.Async.drainQueues (/Users/blagovest/Dropbox/Outside Projects/xxx-gh/node_modules/email-templates/node_modules/bluebird/js/release/async.js:17:14)
[2]     at runCallback (timers.js:566:20)
[2]     at tryOnImmediate (timers.js:546:5)
[2]     at processImmediate [as _immediateCallback] (timers.js:525:5)

```

**Comment by niftylettuce** [comment]
Wrap it with `try { ... stuff here... } catch (err) { console.log(err) }` and it won't throw.

**Comment by niftylettuce** [comment]
If you're using ES6 + Babel, you can use `async/await` syntax with Promises, or `yield`.

**Comment by acabrera91** [comment]
Hi @blagoberry, 

Maybe you were requiring wrong

This is the correct way:
`require('email-templates').EmailTemplate;`

**Comment by samanmohamadi** [comment]
I Have the Same problem.

**Comment by vipulpandeykv** [comment]
I have the same issue with node version 6.9

"stack": [
    "TypeError: EmailTemplate is not a constructor",
    "    at module.exports.ResellerService.sendUserCreationMail ",
    "    at Array.async.auto.sendEmail 
]
  "level": "error",
  "message": "uncaughtException: EmailTemplate is not a constructor"

**Comment by niftylettuce** [comment]
can you please try v3.1.5? npm install email-templates@latest or yarn add email-templates@latest. this package now supports Node v6.4.0+. I've also updated README with this note that v6.4.0+ is a requirement (instead of 7.x)  also please see v2 to v3 upgrade guide at <https://github.com/niftylettuce/email-templates#v3-breaking-changes>

**Comment by Carel155** [comment]
I tried with 3.1.5 and i get the same isssue, EmailTemplate is not a constructor.

`const EmailTemplate = require('email-templates').EmailTemplate`

`    let template = new EmailTemplate(path.join(__dirname, 'templates', templateName));`

**Comment by niftylettuce** [comment]
Did you see README section with v2 to v3 breaking changes?
